# .github/workflows/ci.yml
# CI for LexiClear (server + frontend)
# Runs on push and pull_request, executes tests and builds for both packages.

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  server:
    name: Server - test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules (server)
        uses: actions/cache@v4
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-node-${{ hashFiles('server/package-lock.json', 'server/package.json') }}
          restore-keys: |
            ${{ runner.os }}-server-node-

      - name: Install dependencies (server)
        run: npm ci

      - name: Run server tests
        run: npm test --silent

      - name: Lint server (if eslint configured)
        if: always()
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
            npx eslint . || true
          else
            echo "No ESLint config found - skipping lint"
          fi

          
